export const Roles = {
  ADMIN: "ADMIN",
  USER: "USER",
  STUDENT: "STUDENT",
  ALUMNI: "ALUMNI",
  STUDENT_PRESIDENT: "STUDENT_PRESIDENT",
  FACULTY: "FACULTY",
  DEAN_ACADEMICS: "DEAN_ACADEMICS",
  DEAN_STUDENT_WELFARE: "DEAN_STUDENT_WELFARE",
  DEAN_HEAD: "DEAN_HEAD",
  MENTOR: "MENTOR",
  DONOR: "DONOR",
  PREMIUM_DONOR: "PREMIUM_DONOR",
};
